#!/bin/bash

PASS=true
STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')

if [[ $STAGED_GO_FILES == "" ]]; then
    exit 0
fi


for file in $STAGED_GO_FILES; do
    golint "-set_exit_status" $file
    if [[ $? == 1 ]]; then 
        PASS=false
    fi
done

go test -v ./...
if [[ $? == 1 ]]; then 
    PASS=false
fi


if ! $PASS; then
    printf "COMMIT FAILED\n"
    exit 1
else
    printf "COMMIT SUCCEEDED\n"
fi

exit 0
